name: Deploy FastAPI Backend to Azure

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Zip backend folder
      run: |
        cd backend
        zip -r ../app.zip .

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: signaipapi
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./app.zip
